# FinOps360 Cost Analysis Configuration

# BigQuery settings
bigquery:
  project_id: finops360-dev-2025
  dataset: test
  table: cost_analysis_new
  avg_table: avg_daily_cost_table

# Dashboard settings
interactive_charts: true

# Output settings
output_dir: reports