# Cloud Spend Management Configuration

# Data sources and paths
data:
  file_path: data/finops_data.csv
  output_dir: output

# Analysis settings
analysis:
  # Time period configuration
  period_type: month  # Options: month, quarter, week, year
  period_value: last  # Use 'last' for most recent period or specify a value (e.g. Mar, Q1, 10, 2024)
  year: current       # Use 'current' for current year or specify a year (e.g. FY2024)
  
  # Environment analysis settings
  nonprod_threshold: 5.0  # Percentage threshold for highlighting high non-prod costs
  
  # Organizational hierarchy for analysis
  # This defines the hierarchy path to analyze from top to bottom
  hierarchy:
    - cto
    - tr_product_pillar_team
    - tr_subpillar_name
    - tr_product
    - application
  
  # Number of entries to show for each level
  top_n_by_level:
    cto: 15            # Show all CTOs (likely less than 15)
    tr_product_pillar_team: 15   # Top 15 pillars
    tr_subpillar_name: 10  # Top 10 subpillars
    tr_product: 10     # Top 10 products
    application: 10    # Top 10 applications
  
  # Default if not specified for a level
  top_n: 10
  
  # Display columns (optional, for customizing report columns)
  # These columns will be used for additional information in reports
  display_columns:
    - environment
    - cloud
    - service_name
    - cost

# Report settings
report:
  generate_html: true
  export_csv: true
  page_title: Cloud Spend Management Report
  company_name: FinOps
  logo_path: ""