# Cloud Spend Management Configuration

# Data sources and paths
data:
  file_path: data/finops_data.csv
  output_dir: output

# Analysis settings
analysis:
  # Time period configuration
  period_type: month  # Options: month, quarter, week, year
  period_value: Mar   # Month name, quarter (Q1-Q4), week number, or year
  year: 2024
  
  # Grouping configuration
  parent_grouping: ORG  # Can be any column in dataset: ORG, TR_PRODUCT, ENV, Cloud, VP, PILLAR, etc.
  parent_grouping_value: Starling  # Default value for the parent grouping
  
  # Child grouping for detailed analysis (Application_Name or any other column)
  child_grouping: Application_Name
  top_n: 10
  include_applications: true

# Report settings
report:
  generate_html: true
  export_csv: true
  page_title: Cloud Spend Management Report
  company_name: Cloud Strategy
  logo_path: ""