# FinOps360 Cost Analysis Configuration - Weekly Analysis Example

# Data sources and paths
data:
  file_path: data/finops_data.csv
  output_dir: output

# Analysis settings
analysis:
  # Time period configuration
  period_type: week    # Options: month, quarter, week, year
  period_value: 11     # Week number (1-53)
  year: 2024
  
  # Grouping configuration
  parent_grouping: Cloud  # Can be ORG, TR_PRODUCT, ENV, or Cloud
  parent_grouping_value: AWS  # Default value for the parent grouping
  
  # Child grouping for detailed analysis (always Application_Name)
  child_grouping: Application_Name
  top_n: 5
  include_applications: true

# Report settings
report:
  generate_html: true
  export_csv: true
  page_title: FinOps360 Weekly Cost Analysis
  company_name: FinOps360
  logo_path: ""