# FinOps360 Cost Analysis Configuration

# BigQuery settings
bigquery:
  project_id: finops360-dev-2025
  dataset: test
  cost_table: cost_analysis_new  # Updated to cost_table to match app expectations
  avg_table: avg_daily_cost_table

# Dashboard settings
charts:
  enabled: true  # Controls whether to use interactive charts

# Data settings
data:
  # Fixed dates for comparisons
  day_current_date: "2025-05-03"    # Current day for comparison
  day_previous_date: "2025-05-02"   # Previous day for comparison
  
  # Fixed week periods
  week_current_start: "2025-04-27"  # Current week start date
  week_current_end: "2025-05-03"    # Current week end date
  week_previous_start: "2025-04-20" # Previous week start date
  week_previous_end: "2025-04-26"   # Previous week end date
  
  # Fixed month periods
  month_current: "2025-04"          # Current month (YYYY-MM)
  month_previous: "2025-03"         # Previous month (YYYY-MM)
  
  top_products_count: 10            # Number of top products to display
  nonprod_percentage_threshold: 30  # Highlight products with nonprod % above this threshold
  display_millions: true           # Display costs in raw values rather than millions

# Output settings
output:
  directory: reports