# FinOps360 Cost Analysis Configuration - Quarter Analysis Example

# Data sources and paths
data:
  file_path: data/finops_data.csv
  output_dir: output

# Analysis settings
analysis:
  # Time period configuration
  period_type: quarter  # Options: month, quarter, week, year
  period_value: Q1      # Quarter (Q1-Q4)
  year: 2024
  
  # Grouping configuration
  parent_grouping: ORG  # Can be ORG, TR_PRODUCT, ENV, or Cloud
  parent_grouping_value: Starling  # Default value for the parent grouping
  
  # Child grouping for detailed analysis (always Application_Name)
  child_grouping: Application_Name
  top_n: 10
  include_applications: true

# Report settings
report:
  generate_html: true
  export_csv: true
  page_title: FinOps360 Quarterly Cost Analysis
  company_name: FinOps360
  logo_path: ""