# FinOps360 Cost Analysis Configuration - Annual Analysis Example

# Data sources and paths
data:
  file_path: data/finops_data.csv
  output_dir: output

# Analysis settings
analysis:
  # Time period configuration
  period_type: year    # Options: month, quarter, week, year
  period_value: 2024   # Year number
  year: 2024           # Not used for year analysis
  
  # Grouping configuration
  parent_grouping: TR_PRODUCT  # Can be ORG, TR_PRODUCT, ENV, or Cloud
  parent_grouping_value: ETL/ELT Jobs  # Default value for the parent grouping
  
  # Child grouping for detailed analysis (always Application_Name)
  child_grouping: Application_Name
  top_n: 15
  include_applications: true

# Report settings
report:
  generate_html: true
  export_csv: true
  page_title: FinOps360 Annual Cost Analysis
  company_name: FinOps360
  logo_path: ""