# Cloud Spend Management Configuration

# Data sources and paths
data:
  file_path: archive/data/finops_data.csv  # CSV data path (used when not using BigQuery)
  output_dir: output

# BigQuery settings (used when --use-bigquery is passed)
bigquery:
  project_id: finops360-dev-2025
  dataset: test
  table: cost_analysis_new
  avg_table: avg_daily_cost_table
  use_bigquery: true  # Set to true to enable BigQuery as data source
  use_bqdf: true      # Set to false to disable BigQuery DataFrames
  selected_columns:   # List of columns to fetch (reduces data transfer)
    # All fields from new schema
    - date
    - cto
    - cloud
    - tr_product_pillar_team
    - tr_subpillar_name
    - tr_product_id
    - tr_product
    - managed_service
    - environment
    - cost
  avg_columns:        # Columns from average daily cost table
    - date
    - environment_type
    - cto
    - fy24_avg_daily_spend
    - fy25_avg_daily_spend
    - fy26_ytd_avg_daily_spend
    - fy26_forecasted_avg_daily_spend
    - fy26_avg_daily_spend
    - daily_cost

# Analysis settings
analysis:
  # Time period configuration
  period_type: month  # Options: month, quarter, week, year
  period_value: last  # Use 'last' for most recent period or specify a value (e.g. Mar, Q1, 10, 2024)
  year: current       # Use 'current' for current year or specify a year (e.g. FY2024)
  
  # Environment analysis settings
  nonprod_threshold: 5.0  # Percentage threshold for highlighting high non-prod costs
  
  # Organizational hierarchy for analysis
  # This defines the hierarchy path to analyze from top to bottom
  hierarchy:
    - cto
    - tr_product_pillar_team
    - tr_product

  
  # Number of entries to show for each level
  top_n_by_level:
    cto: 15            # Show all CTOs (likely less than 15)
    tr_product_pillar_team: 15   # Top 15 pillars
    tr_product: 10     # Top 10 products
  
  # Default if not specified for a level
  top_n: 10
  
  # Display columns (optional, for customizing report columns)
  # These columns will be used for additional information in reports
  display_columns:
    - environment
    - cloud
    - managed_service
    - cost

# Report settings
report:
  generate_html: true
  export_csv: true
  page_title: Cloud Spend Management Report
  company_name: FinOps
  logo_path: ""